# Generated by Django 3.1.7 on 2021-03-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_answer',
            field=models.CharField(default='security answer', max_length=30, verbose_name='security answer'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(default='security question', max_length=50, verbose_name='security question'),
        ),
    ]
