# Generated by Django 3.1.7 on 2021-04-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210420_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='/home/kevin/COMP3900/capstone-project-3900-w18b-quuack-heads/stonk-ponk-be/src/server/media/account/default.img', max_length=255),
        ),
    ]
