# Generated by Django 3.1.7 on 2021-04-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210421_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='/mnt/c/Users/XGaming Systems/Documents/StonkPonk/capstone-project-3900-w18b-quuack-heads/stonk-ponk-be/src/server/media/account/default.img', max_length=255),
        ),
    ]
