# Generated by Django 3.1.7 on 2021-03-29 11:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliostock',
            name='AUD_value',
        ),
        migrations.RemoveField(
            model_name='portfoliostock',
            name='change_7_days',
        ),
        migrations.RemoveField(
            model_name='portfoliostock',
            name='change_today',
        ),
        migrations.RemoveField(
            model_name='portfoliostock',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='stockownership',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='stockownership',
            name='purchase_date',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('stockOwnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.stockownership')),
            ],
        ),
    ]
