# Generated by Django 3.1.7 on 2021-03-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210329_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchase_vol',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockownership',
            name='VWAP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockownership',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
