# Generated by Django 3.1.7 on 2021-04-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210401_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockownership',
            name='first_purchase',
            field=models.DateField(null=True),
        ),
    ]
